name: zero1fivehundred
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2557347484398633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#f6f6f6'
    - '#6e6e6c'
    - '#bbbbb9'
    - '#888886'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
